# NumPy Indexing and Selection

Here we will discuss how to select elements or groups of elements from an array.

In [1]:
import numpy as np

In [2]:
#Creating sample array
arr = np.arange(0,21)

In [3]:
#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [6]:
#Get a value at an index
arr[9]

9

In [8]:
arr[12:17]

array([12, 13, 14, 15, 16])

In [7]:
arr[0:9]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [9]:
#Get values in a range
arr[0:11:2] # start stop step

array([1, 3, 5, 7, 9])

## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [9]:
li = [1,2,3]


In [10]:
li*2

[1, 2, 3, 1, 2, 3]

In [11]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [12]:
arr*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40])

In [ ]:
#array element wise operation can be done this property of array is called as broadcasting

In [6]:
l1=[1,2,3,4]


In [7]:
l1*2

[1, 2, 3, 4, 1, 2, 3, 4]

In [8]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [9]:
arr*4# Broadcasting means element wise operation

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64,
       68, 72, 76, 80])

In [10]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [14]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [13]:
#Setting a value with index range (Broadcasting)
arr[1:6]=10000

In [14]:
arr

array([    0, 10000, 10000, 10000, 10000, 10000,     6,     7,     8,
           9,    10,    11,    12,    13,    14,    15,    16,    17,
          18,    19,    20])

In [15]:
arr1=arr ## taking backup

In [16]:
arr1[1:6]=500

In [17]:
arr1

array([  0, 500, 500, 500, 500, 500,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20])

In [18]:
arr

array([  0, 500, 500, 500, 500, 500,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20])

Now note the changes also occur in our original array So to take backups
donot use assignment operator.Instead use copy function

In [19]:
arr

array([  0, 500, 500, 500, 500, 500,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20])

Data is not copied, it's a view of the original array! This avoids memory problems!

In [20]:
#To get a copy, we need to be explicit
arr_copy = arr.copy()
arr_copy

array([  0, 500, 500, 500, 500, 500,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20])

In [21]:
arr_copy[1:6]=600

In [22]:
arr_copy

array([  0, 600, 600, 600, 600, 600,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20])

In [23]:
arr

array([  0, 500, 500, 500, 500, 500,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20])

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.

In [29]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [30]:
arr_2d[0,2]

15

In [25]:
arr_2d[1,1]

25

In [26]:
arr_2d[2,2]

45

In [28]:
arr_2d[1,0]

20

In [27]:
arr_2d.shape

(3, 3)

In [28]:
#Indexing to get 25

arr_2d[1,2]

30

In [29]:
arr_2d[2,2]

45

In [31]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [34]:
arr_2d[1:,1:]

array([[25, 30],
       [40, 45]])

In [36]:
arr_2d[0:,1:]

array([[10, 15],
       [25, 30],
       [40, 45]])

In [37]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [40]:
arr_2d[0:2,0:2]

array([[ 5, 10],
       [20, 25]])

In [45]:
arr_2d[0:2,1:]

array([[10, 15],
       [25, 30]])

In [30]:
arr_2d[0,1]

10

In [24]:
arr_2d[1,0]

NameError: name 'arr_2d' is not defined

In [46]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [49]:
arr_2d[0:,2:]

array([[15],
       [30],
       [45]])

In [39]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

20

In [98]:
# Getting individual element value
arr_2d[1,0]

20

In [41]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [34]:
arr_2d[0:2,1:]

array([[10, 15],
       [25, 30]])

In [35]:
arr_2d[0:,1:]

array([[10, 15],
       [25, 30],
       [40, 45]])

In [40]:
arr_2d[1:,0:2]

array([[20, 25],
       [35, 40]])

In [38]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [27]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[0:2,0:2]

array([[ 5, 10],
       [20, 25]])

In [31]:
arr_2d[1:,1:2]

array([[25],
       [40]])

In [43]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [52]:
arr_2d[1:,1:]

array([[25, 30],
       [40, 45]])

In [29]:
arr_2d[:,:1]

array([[ 5],
       [20],
       [35]])

In [44]:
arr_2d[1:,1:]

array([[25, 30],
       [40, 45]])

In [45]:
arr_2d[0:2,1:]

array([[10, 15],
       [25, 30]])

In [33]:
arr_2d[0:,0:1] ## extracting the columns

array([[ 5],
       [20],
       [35]])

In [34]:
arr_2d[:,:1]

array([[ 5],
       [20],
       [35]])

In [ ]:
arr_2d[0:,:1]

In [10]:
arr_2d[0:,2:]

array([[15],
       [30],
       [45]])

In [ ]:
# Task:- give 5,20,34 i.e first column

In [20]:
arr2d[[2,4,6,8,9]] ## random row indexing

array([[2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9.]])

In [7]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Happy Learning!