# NumPy 
NumPy is a Linear Algebra Library in Python and it is the holy grail and the main building block of Data Science using Python. Almost all the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

It is bound to several C libraries which makes NumPy one of the fastest libraries in Python.

We will learn the basics of NumPy, to get started we need to install it!

## Installation Instructions

**It is highly recommended you install Python using the Anaconda distribution to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up with the use of a conda install. If you have Anaconda, install NumPy by going to your terminal or command prompt and typing:**
    
    conda install numpy
    
**If you do not have Anaconda and can not install it, please refer to [Numpy's official documentation on various installation instructions.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)**

In [ ]:
!pip install numpy


[notice] A new release of pip is available: 23.0.1 -> 23.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


## Using NumPy

Once you've installed NumPy you can import it as a library:

In [ ]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. 

# Numpy Arrays

Numpy arrays essentially of two types: vectors and matrices. Vectors are strictly 1-D arrays and matrices are 2-D (Note: A matrix can still have only one row or one column).

The following cells explain on creation of NumPy arrays.

## Creating NumPy Arrays

### From a Python List

An array can be created by directly converting a list or list of lists:

In [ ]:
my_list = [1,2,3,4,5,6]
my_list

[1, 2, 3, 4, 5, 6]

In [ ]:
a=np.array(my_list)

In [ ]:
a

array([1, 2, 3, 4, 5, 6])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
a.shape

(6,)

In [ ]:
a.shape

(6,)

In [ ]:
a.ndim

1

In [ ]:
a = np.array([1,2,3])

In [ ]:
a = np.array([[[1,2,3],[3,4,4],[5,9,8,9]]])

C:\Users\Datamites\AppData\Local\Temp\ipykernel_11712\4096370704.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a = np.array([[[1,2,3],[3,4,4],[5,9,8,9]]])


In [ ]:
a.ndim


2

In [ ]:
a.shape

(1, 3)

In [ ]:
a

array([1, 2, 3])

In [ ]:
a.shape

(3,)

In [ ]:
a = [[1,2,3],[4,5,6]]

In [ ]:
a = np.array(a)

In [ ]:
a.shape

(2, 3)

In [ ]:
a = [[1,2,3],[4,5,6]]

In [ ]:
b = np.array([[[[[1,2,3],[1,2,3],[4,5,6],[3,4,5]]]]])

In [ ]:
b.ndim

5

In [ ]:
b = np.array([[[[[[1,2,3],[1,2,3],[4,5,6],[3,4,5]]]]]])

NameError: ignored

In [ ]:
import numpy as np

In [ ]:
a = np.array(a)

In [ ]:
a.shape

(2, 3)

In [ ]:
a = [[1,2,3],[4,5,6]]

In [ ]:
a = np.array(a)

In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a.shape

(2, 3)

In [ ]:
a =[[[1,2,3],[4,5,6]]]

In [ ]:
import numpy as np

In [ ]:
a = np.array(a)

In [ ]:
a

array([[[1, 2, 3],
        [4, 5, 6]]])

In [ ]:
a.shape

(1, 2, 3)

In [ ]:
b=[[[[1,2,3],[4,5,6]]]] 

In [ ]:
b = np.array(b)

In [ ]:
b.shape

(1, 1, 2, 3)

In [ ]:
my_matrix = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
my_matrix.size

AttributeError: ignored

In [ ]:
b=np.array(my_matrix)

In [ ]:
b.shape

(3, 4)

In [ ]:
b.ndim # dimensions

2

In [ ]:
b.size # how many elements are present

12

In [ ]:
b.dtype # data type

dtype('int32')

In [ ]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
# Array summary
print('The Dimenesion of array is:',b.ndim)
# dimensions of given array


print('The size of array:',b.size) 
# Number of elements in array

print('The datatype of element:',b.dtype) 
# Datatype of elements of array

print('The datatype of array',type(b))

print('The shape:',b.shape)



The Dimenesion of array is: 2
The size of array: 12
The datatype of element: int32
The datatype of array <class 'numpy.ndarray'>
The shape: (3, 4)


In [ ]:
import warnings
warnings.filterwarnings('ignore')

In [ ]:
a = np.array(my_matrix)

In [ ]:
a


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a.shape

(3, 4)

In [ ]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [ ]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
range(10)

In [ ]:
np.arange(0,15,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [ ]:
import numpy as np

In [ ]:
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
np.arange(0,15) # Start end

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
np.arange(0,11,5) # Start stop step

array([ 0,  5, 10])

In [ ]:
#create an even an numbers between 1 to 100

### zeros and ones

Generate arrays of zeros or ones

In [ ]:
q=np.zeros((1,1,3,1),dtype=int)

In [ ]:
q

array([[[[0],
         [0],
         [0]]]])

In [ ]:
a = np.zeros(4,dtype=int)

In [ ]:
a

array([0, 0, 0, 0])

In [ ]:
q

array([0, 0, 0, 0])

In [ ]:
a = np.zeros((2,4),dtype=int)

In [ ]:
a

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
#dtype is default as float to change the dtype use 'dtype=int'

In [ ]:
q = np.zeros(6,dtype=int)

In [ ]:
q

array([0, 0, 0, 0, 0, 0])

# ones

In [ ]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.ones((3,3,3),dtype=int)

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

### linspace
Return evenly spaced numbers over a specified interval.

In [ ]:
a = np.arange(10)

In [ ]:
a

array([0, 1, 2, 3, 4])

In [ ]:
np.linspace(5,20)

array([ 5.        ,  5.30612245,  5.6122449 ,  5.91836735,  6.2244898 ,
        6.53061224,  6.83673469,  7.14285714,  7.44897959,  7.75510204,
        8.06122449,  8.36734694,  8.67346939,  8.97959184,  9.28571429,
        9.59183673,  9.89795918, 10.20408163, 10.51020408, 10.81632653,
       11.12244898, 11.42857143, 11.73469388, 12.04081633, 12.34693878,
       12.65306122, 12.95918367, 13.26530612, 13.57142857, 13.87755102,
       14.18367347, 14.48979592, 14.79591837, 15.10204082, 15.40816327,
       15.71428571, 16.02040816, 16.32653061, 16.63265306, 16.93877551,
       17.24489796, 17.55102041, 17.85714286, 18.16326531, 18.46938776,
       18.7755102 , 19.08163265, 19.3877551 , 19.69387755, 20.        ])

In [ ]:
#if I want to know the interval use retstep = True

In [ ]:
np.linspace(5,20)

(array([ 5.        ,  5.30612245,  5.6122449 ,  5.91836735,  6.2244898 ,
         6.53061224,  6.83673469,  7.14285714,  7.44897959,  7.75510204,
         8.06122449,  8.36734694,  8.67346939,  8.97959184,  9.28571429,
         9.59183673,  9.89795918, 10.20408163, 10.51020408, 10.81632653,
        11.12244898, 11.42857143, 11.73469388, 12.04081633, 12.34693878,
        12.65306122, 12.95918367, 13.26530612, 13.57142857, 13.87755102,
        14.18367347, 14.48979592, 14.79591837, 15.10204082, 15.40816327,
        15.71428571, 16.02040816, 16.32653061, 16.63265306, 16.93877551,
        17.24489796, 17.55102041, 17.85714286, 18.16326531, 18.46938776,
        18.7755102 , 19.08163265, 19.3877551 , 19.69387755, 20.        ]),
 0.30612244897959184)

In [ ]:
np.linspace(1,10,10)#retstep=True,dtype=int)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
# The step size in linspace is automateically adjusted based on number of elements
# requested in the array

## eye

Creates an identity matrix

In [ ]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

## Reshape
Returns an array containing the same data with a new shape. Here m x n should be equal to other number of elements in the array.

In [ ]:
a = np.arange(1,21)

In [ ]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
a.shape

(20,)

In [ ]:
b=a.reshape(1,1,5,4)

In [ ]:
b.ndim

4

In [ ]:
a.reshape(2,10) # converting into 2 d

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [ ]:
a.reshape(1,5,4) # converting int0 3d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20]]])

In [ ]:
a.reshape(4,5,1)

array([[[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5]],

       [[ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]],

       [[11],
        [12],
        [13],
        [14],
        [15]],

       [[16],
        [17],
        [18],
        [19],
        [20]]])

In [ ]:
a.reshape(1,1,4,5)

array([[[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10],
         [11, 12, 13, 14, 15],
         [16, 17, 18, 19, 20]]]])

In [ ]:
a.reshape(4,1,1,5)

array([[[[ 1,  2,  3,  4,  5]]],


       [[[ 6,  7,  8,  9, 10]]],


       [[[11, 12, 13, 14, 15]]],


       [[[16, 17, 18, 19, 20]]]])

In [ ]:
a.reshape(5,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [ ]:
a.reshape(1,5,3,1)

array([[[[ 1],
         [ 2],
         [ 3]],

        [[ 4],
         [ 5],
         [ 6]],

        [[ 7],
         [ 8],
         [ 9]],

        [[10],
         [11],
         [12]],

        [[13],
         [14],
         [15]]]])

In [ ]:
arr1.shape

(20,)

In [ ]:
a = np.arange(1,16)

In [ ]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
a.reshape(1,3,5,1)

array([[[[ 1],
         [ 2],
         [ 3],
         [ 4],
         [ 5]],

        [[ 6],
         [ 7],
         [ 8],
         [ 9],
         [10]],

        [[11],
         [12],
         [13],
         [14],
         [15]]]])

In [ ]:
arr1.reshape(5,4) ##  possible

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
arr1.reshape(4,5)

In [ ]:
arr.reshape(2,10)

In [ ]:
arr.reshape(10,2)

In [ ]:
# Task reshape arr2

### max,min,argmax,argmin

These are useful methods for finding max or min values.
Or to find their index locations using argmin or argmax

In [ ]:
arr = np.arange(1,23)

In [ ]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22])

In [ ]:
arr.max() ## gives maximum value of element

22

In [ ]:
arr.argmax()  ## gives index location of maximum value

21

In [ ]:
arr.min() ##gives minimum value of element

1

In [ ]:
arr.argmin() ## gives location of minimum value.

0

# Happy Learning!